Add : [User App] Category View
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #12
Opened 2021-05-17 08:12 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
카테고리, 세부 카테고리 json response하는 view 구현
		 
## 수정 사항들 자세한 내용
메인 페이지에서 메뉴창을 눌렀을 때 카테고리와 세부 카테고리를 보내는 view 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 13:22 UTC, Kang-kyunghun requested changes

2021-05-17 13:22 UTC, Kang-kyunghun commented on load_csv.py
> +import csv
업로드 파일은 제거해 주세요.

2021-05-17 13:22 UTC, Kang-kyunghun commented on product/views.py
> +        return JsonResponse({'category':category_list,'sub_category':sub_category_list}, status=200)
.values를 사용하지 않고, list comprehension으로 바꿔보세요~

2021-05-18 08:24 UTC, tonic523 commented on product/views.py
> +        return JsonResponse({'category':category_list,'sub_category':sub_category_list}, status=200)
comprehension으로 바꾸니 위 아래 구조가 통일돼서 가독성이 좋은 것 같습니다

2021-05-19 09:23 UTC, Kang-kyunghun requested changes

2021-05-19 09:23 UTC, Kang-kyunghun commented on product/views.py
> +            category_list.append(
이 부분까지 list comprehesion으로 바꿀 수 있지 않을까요?

2021-05-19 10:31 UTC, tonic523 commented on product/views.py
> +            category_list.append(
categorys로 for문을 돌리면서 category 리스트랑 sub_category 리스트 두개를 만들고 싶은데
category list를 comprehesion으로 하면 제 생각으로는 category를 두번 돌려야 되는 로직만 생각납니다 ㅠㅠ
더 나은 방법이 있는건가요?
```python
category_list = [
            {
                'id'          : category.id,
                'korean_name' : category.korean_name,
                'english_name': category.english_name
            }
            for category in categorys
        ]

for category in categorys:
    sub_category_list[category.korean_name] = [
        {
            'id'          : sub_category.id,
            'korean_name' : sub_category.korean_name,
            'english_name': sub_category.english_name
        }
        for sub_category in SubCategory.objects.filter(category=category)
    ]

```

2021-05-20 01:24 UTC, Kang-kyunghun requested changes

2021-05-20 01:24 UTC, Kang-kyunghun commented on product/views.py
> +            ]
```suggestion
        category_list = [
            {
                'id'          : category.id,
                'korean_name' : category.korean_name,
                'english_name': category.english_name,
                'sub_categories' : [{
                    'id'          : sub_category.id,
                    'korean_name' : sub_category.korean_name,
                    'english_name': sub_category.english_name
                }for sub_category in category.sub_category_set.all()]
            }for category in categorys
        ]
```

2021-05-20 01:24 UTC, Kang-kyunghun commented on product/views.py
> +            ]
이렇게 바꿀 수 있을 것 같아요

2021-05-20 01:25 UTC, Kang-kyunghun commented
불필요한 파일 제거 하세요~~!!

2021-05-20 02:01 UTC, tonic523 commented on product/views.py
> +            ]
아 넵! json 구조가 바뀌는거라 프론트분과 상의해보고 결정해보겠습니다

2021-05-20 05:10 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-20 05:10 UTC, merged