Add : [Product App] Product DetailView 작성
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #13
Opened 2021-05-17 08:14 UTC by Action2theFuture

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Product Detail 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- path parameter를 통한 상품 상세내용 나타내는 기능 구현
- random 함수를 이용하여 추천상품에 대한 리스트 랜덤으로 나타나는 로직 
- 상품 상세페이지 내에 상품이름, 가격, 이미지, 재고상황 나타남
- 
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 13:22 UTC, Kang-kyunghun requested changes

2021-05-17 13:22 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/p/<str:product_name>', ProductDetailView.as_view()),
- restfull하게 바꿔주세요.
- path 파라미터는 주로 pk를 사용합니다.

2021-05-17 13:22 UTC, Kang-kyunghun commented on product/views.py
> +class ProductDetailView(View):
- product 상제 페이지 아닌가요? append가 있는 이유를 서명해 주세요. 
- path 파라미터로 id를 받아와서 Product 객체로만 데이터를 구성해 보세요. 불필요하게 데이터베이스에 계속 접근하고 있습니다.

2021-05-18 02:55 UTC, Kang-kyunghun requested changes

2021-05-18 02:55 UTC, Kang-kyunghun commented on product/views.py
> +        return JsonResponse({'MASSAGE':'Non-existent Product'}, status=404)
키 값은 소문자로 해주세요.

2021-05-18 02:55 UTC, Kang-kyunghun commented on product/views.py
> +                'color':color_list,
컨벤션 맞춰주세요.

2021-05-18 02:55 UTC, Kang-kyunghun commented on product/views.py
> +        if Product.objects.filter(id=pk).exists():
- values을 너무 남용 하는 것으로 보입니다.
- path 파마미터로 받은 pk을 이용하면 해당 Product의 인스턴스를 가져올 수 있습니다. 그리고 나서 product 인스턴스로부터 시작해서 필요한 정보들을 가져오세요. 
ex) images = product.imeage_set.all()

2021-05-18 02:55 UTC, Kang-kyunghun commented on product/views.py
> +            random_number         = random.randrange(1,SubCategory.objects.count()+1)
제품 id가 1번부터 있다는 보장에 대해 코멘트로 설명하세요.

2021-05-18 06:03 UTC, Action2theFuture commented on product/views.py
> +        if Product.objects.filter(id=pk).exists():
model.py에서 수정할 부분이 생겨서 반영이 되면 조치하도록 하겠습니다!

2021-05-18 06:03 UTC, Action2theFuture commented on product/views.py
> +            random_number         = random.randrange(1,SubCategory.objects.count()+1)
추천 상품을 제시하는 기능을 따로 branch를 만들어서 PR보내도록 하겠습니다

2021-05-19 09:41 UTC, Kang-kyunghun requested changes

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/detail/', ProductDetailView.as_view()),
상세페이지 같은 경우 products의 특정 id로 찾아 갑니다.
이에 따라 view에서도 수정이 필요하겠죠?
```suggestion
    path('/<int:pdoruct_id>', ProductDetailView.as_view()),
```

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +            return JsonResponse({'massage':f'{e}'}, status=404)
validation이 사용되는 구간이 있나요? 필요 없는 예외처리면 제거해 주세요.

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +    def get(self ,request):
```suggestion
    def get(self ,request, product_id):
```
path parameter로 상품의 id를 받기 위해서는 다음과 같이 수정이 필요합니다.

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +            pk = request.GET.get('id',None)
path 파라미터로 받으면 필요 없어지겠죠?

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +            if pk is not None:
있는 경우가 아닌 없는 경우를 먼저 판단해서 예외처리하면 조금 더 깔끔해 집니다.
```suggestion
            if Product.objects.filter(id=product_id).exists():
                return JsonResponse({'message': 'NOT_FOUND'}, status=404)
```

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +                product_list = Product.objects.filter(id=pk).values()
상세 페이지를 가져오는 view니까 필요 없어 보입니다.

2021-05-19 09:41 UTC, Kang-kyunghun commented on product/views.py
> +                    }]
```suggestion
                result = 
                    {
                    'id'            : product.id,
                    'korean_name'   : product.korean_name,
                    'english_name'  : product.english_name,
                    'price'         : int(product.price),
                    'stock'         : product.stock,
                    'is_new'        : product.is_new,
                    'url'           : [image.url for image in product.image.all()],
                    'descriptions'  : list(descriptions),
                    'star'          : uniform(0.0,5.0),
                    'breadcrumb'    : [
                        product.sub_category.category.korean_name, 
                        {'id':product.sub_category.id, 
                        'name':product.sub_category.korean_name}, 
                        product.korean_name]
                    }
```
- 제품 정보 하나만 보내기 때문에 list에 안 담고 바로 딕셔러리로 보내면 될 것 같습니다.
- image url 가져오는 방법 수정해 봤는데, 참고해 보세요.
- breadcrumb의 내용과 데이터를 보내는 이유를 코멘트로 남겨주세요.

2021-05-19 09:41 UTC, Kang-kyunghun commented on load_csv.py
> +import csv
여전히 디테일뷰에는 제거 되지 않았습니다.

2021-05-19 10:26 UTC, Action2theFuture commented on product/urls.py
> +    path('/detail/', ProductDetailView.as_view()),
query parameter로 접근을 하였는데 이러한 상황은 path로 갖춰지는게 더 좋은 방법인건가요?

2021-05-19 10:34 UTC, Action2theFuture commented on product/views.py
> +                    }]
1. 프론트 쪽에서 json을 리스트로 받아야 매핑이 가능하다고하여 리스트로 보냈습니다
2. 잘못된 코드였던 것 같습니다 수정하겠습니다
3. 이것도 비슷한 이유인데 breadcrumb를 구현하고 싶어서 리스트로 받아 인덱싱 할 수 있도록 재구성하여 보냈습니다

> ![image](https://user-images.githubusercontent.com/74296888/118798917-24381000-b8d9-11eb-894b-cf4f49a8744f.png)

2021-05-20 05:11 UTC, Kang-kyunghun requested changes
conflict 해결하면서 공백 하나만 추가해 주세요.

2021-05-20 05:11 UTC, Kang-kyunghun commented on product/views.py
> +        product      = Product.objects.get(id=product_id)
```suggestion
            return JsonResponse({'massage':'non-existent product'}, status=404)
            
        product      = Product.objects.get(id=product_id)
```

2021-05-20 09:53 UTC, Kang-kyunghun commented
고생 많으셨습니다.

2021-05-20 09:53 UTC, merged