Add : [Product App] Main Page View 작성
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #14
Opened 2021-05-17 08:31 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- main page view 추가
		 
## 수정 사항들 자세한 내용
- 세부 카테고리 중 랜덤으로 하나를 선택해 추천 상품 list response
- 신상품은 view에서 6개를 직접 작성하여 6개의 신상품을 이미지에 맞추어  response

## 기타 질문 및 특이 사항
신상품은 프론트쪽에서 배경 이미지에 맞는 상품을 주어야 하는 상황입니다. 배경 이미지에 맞는 상품을 product model에 image를 추가해서 filter로 거르는 방법과 배경 이미지에 맞는 상품을 직접 입력하여 주는 방법이 있습니다. 
2가지 방법 모두 6개의 상품만 한정적으로 사용한다고 생각해서 두 번째 방법을 선택하여 사용했는데 하드 코드적인 면이 있어 고민이 됩니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 13:21 UTC, Kang-kyunghun requested changes

2021-05-17 13:21 UTC, Kang-kyunghun commented on load_csv.py
> +import csv
업로더 파일은 제거하고 올려주세요.

2021-05-17 13:21 UTC, Kang-kyunghun commented on product/views.py
> +        right_image_storage = Product.objects.get(english_name="adidasstorage")
상품이 정해져 있다고 해도, 정해진 상품이 바뀔 때마다 소스코드를 수정해야 되게 상품을 가져오지 않습니다. 
예를 들어 신상품이면 등록된 순서로 order_by해서 몇개 이런식으로 가야합니다.

2021-05-17 13:21 UTC, Kang-kyunghun commented on product/views.py
> +                },
똑같은 구조가 반복되고 있습니다. 불필요합니다.

2021-05-17 13:21 UTC, Kang-kyunghun commented on product/views.py
> +        random_number      = random.randrange(1,Category.objects.count()+1)
id가 1번부터 항상 연속적으로 존재한다는 보장이 있을까요?

2021-05-18 00:56 UTC, tonic523 commented on product/views.py
> +        random_number      = random.randrange(1,Category.objects.count()+1)
카테고리 쿼리셋을 리스트로 바꾸어 리스트의 인덱스를 랜덤으로 지정하여 카테고리 객체 하나를 가져오는 방식으로 바꾸겠습니다.

2021-05-18 08:31 UTC, tonic523 commented on product/views.py
> +        random_number      = random.randrange(1,Category.objects.count()+1)
main view를 category branch, new_product branch로 분류해서 다시 PR로 보내고 싶은데 리뷰 해주신것들 반영해서 다시 PR 올려도 괜찮을까요?

2021-05-20 05:30 UTC, closed without merging