Add : [Product App] Product List
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #15
Opened 2021-05-17 10:37 UTC by Action2theFuture

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Product List 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Product list 기능 구현
- Pagenation offset,limit을 이용하여 Query parameter를 통해  기능 구현
- filter, sort 로직 구현
- path parameter를 이용하여 해당 subcategory를 가지고 있는 product 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 13:27 UTC, Kang-kyunghun requested changes
필터 없는 수순 product list만 반환하는 view 코드로만 해서 다리 올려주세요.

2021-05-17 13:27 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/cat/<str:sub_category_name>/', ProductListView.as_view()),
같은 url이 2개 존재합니다. 그리고 restfull하게 고쳐주세요.

2021-05-17 13:27 UTC, Kang-kyunghun commented on product/views.py
> +
불필요한 공백입니다.

2021-05-17 13:27 UTC, Kang-kyunghun commented on product/views.py
> +            return product_list
이 함수들이 다른 view에서 사용 되나요? 만약 다른 view에서 사용 된다고 하면 아예 모듈화 해야 된다고 생각 됩니다. 
코드가 길어진다는 이유로 따로 분리 시킨 것 같은데, 오히려 view 자체의 가독성을 떨어뜨립니다.

2021-05-19 09:51 UTC, Kang-kyunghun requested changes

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/list/', ProductListView.as_view()),
```suggestion
    path('', ProductListView.as_view()),
```
8000/products 가 products의 자원을 가리키기 때문에 다음과 같이 수정하면 좋을 것 같습니다.

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +                        'image'             : [image.url for image in list(product.image.all())],
```suggestion
                        'image'             : [image.url for image in product.image.all()],
```
list로 다시 안 감싸도 될 것 같은데요? color에서 했던 것 처럼 하면 될 것 같아요.

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +                        products = products[(page_number-1)*VIEW_PRODUCTS:]
페이지 네이션 때문이 있는 건가요??

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +
reduce을 사용한 이유를 코멘트로 남겨주세요.

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +            print(queryList)
print 제거해 주세요.

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +                return JsonResponse({'massage':'non-existent sub_Category_name key'}, status=404)
존재 여부 판단 전에 데이터를 먼저 조회 하는데, 순서가 바껴야 할 것 같고, 그 전에 SubCategory 객체를 가져오는게 해당 SubCategory에 속해 있는 products을 가져 오기 위함인가요?

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +            sort_list    = {'PRICE_LOW_TO_HIGH':'price','PRICE_HIGH_TO_LOW':'-price','NEWEST':'is_new','NAME_ASCENDING':Lower('ko_name')}
:을 기준으로 정렬해 주세요

2021-05-19 09:51 UTC, Kang-kyunghun commented on product/views.py
> +            print(fields)
print 제거해 주세요.

2021-05-19 10:09 UTC, Action2theFuture commented on product/views.py
> +                        products = products[(page_number-1)*VIEW_PRODUCTS:]
네 페이지네션을 만들었습니다!

2021-05-19 10:13 UTC, Action2theFuture commented on product/views.py
> +
reduce 함수를 사용하여 Q객체를 가진 리스트를 단일값으로 반환하기 위해서 사용하였습니다

2021-05-19 10:52 UTC, Action2theFuture commented on product/views.py
> +                return JsonResponse({'massage':'non-existent sub_Category_name key'}, status=404)
subcategory를 받아와 해당 하는 상품들을 조회하는 페이지의 파라미터에서 해당 카테고리의  englishname을 가져와 조회하는 페이지여서 product로 subcategory를 가져오는 것보다 subcategory의 필드에서 가져오는 것이 가독성이 좋아보이고 간단하게 사용할 수 있는 코드로 생각했습니다 

```
result = [{ 
                        'id'                : product.id,
                        'korean_name'       : product.korean_name,
                        'english_name'      : product.english_name,
                        'price'             : product.price,
                        'special_price'     : product.special_price,
                        'is_new'            : product.is_new,
                        'color_list'        : [color.name for color in products.color.all()],
                        'sub_category_name' : sub_category.korean_name,
                        'sub_category_url'  : sub_category.english_name,
                        'image'             : [url['url'] for url in product.image.values('url')],
                        'series'            : product.series.korean_name,
                        'content'           : sub_category.content,
                        'star'              : uniform(0.0,5.0)
                    } for product in products]
```

2021-05-20 11:37 UTC, Kang-kyunghun commented
고생하셨습니다~~!!

2021-05-20 11:37 UTC, merged