Add : [Order App] Orderlist, OrderQuantity view 작성
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #16
Opened 2021-05-17 12:17 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- OrderList 출력 구현
- Orderlist 수량 추가 기능 구현		 
## 수정 사항들 자세한 내용
장바구니에서 주문목록에 대한 상품 데이터를 전달한다.
주문목록에 수량을 수정할 때 OrderList의 객체에 quantity가 바뀌고 장바구니에서 총합 계산을 반환한다.

## 기타 질문 및 특이 사항
장바구니(OrderList)구현을 할 때 가격의 합계에 대해서 질문이 있습니다.
서버에서 통신하면서 총합을 계산해서 주는 것과 프론트에서 주문 상품에 대한 총합을 계산하는 것 중 어느 것이 나은 방법인가요?
일단 서버에서 통신할 때 가격의 총합을 계산하여 보내주게 했는데 저번에 말씀하신 데이터를 기준으로 view를 나눈다기 보다 장바구니라는 페이지를 기준으로 view가 작성되는 것 같습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 13:31 UTC, Kang-kyunghun requested changes

2021-05-17 13:31 UTC, Kang-kyunghun commented on order/views.py
> +                total_order_price += product.price * order_product.quantity
aggregate(Sum('field_name')) 을 이용해서 구해보세요.

2021-05-17 13:31 UTC, Kang-kyunghun commented on order/urls.py
> +    path('/quantity', OrderQuantityView.as_view())
restfull하게 작성하려면 어떻게해야 할지 생각해 보세요.

2021-05-17 13:31 UTC, Kang-kyunghun commented on order/views.py
> +                )
list comprehension으로 바꿔주세요.

2021-05-17 13:31 UTC, Kang-kyunghun commented on order/views.py
> +            return HttpResponseRedirect('/orderlist')
리다이렉트를 하는 이유를 코멘트로 남겨주세요.

2021-05-17 13:31 UTC, Kang-kyunghun commented on order/views.py
> +class OrderQuantityView(View):
결국 이 view는 cart(order item)을 수정하는 view로 보여지는데, 이에 맞게 view 이름과 url 수정해 주세요.

2021-05-18 02:56 UTC, Kang-kyunghun requested changes

2021-05-18 02:56 UTC, Kang-kyunghun commented on order/views.py
> +
불필요한 공백 제거해 주세요.

2021-05-18 15:43 UTC, tonic523 commented on order/views.py
> +            return HttpResponseRedirect('/orderlist')
수량을 바꾸는 view를 호출할 때마다 총합 가격을 계산해주기 위해 리다이렉트를 썼습니다.
쿼리 파라미터를 사용하면 2번 호출할 필요없이 갯수가 변화될 때 같은 뷰를 호출하게 만들 예정입니다.

2021-05-20 09:57 UTC, Kang-kyunghun commented
테스트 결과 첨부해 주세요.

2021-05-20 10:04 UTC, tonic523 commented
```json
{
order_list: [
{
order_id: 1,
id: 1,
english_name: "BOJA",
korean_name: "뵈야",
sub_category: "작업등",
price: 30000,
url: "/images/products/lamps/10-r png.png",
quantity: 3
},
{
order_id: 2,
id: 2,
english_name: "FADO",
korean_name: "파도",
sub_category: "작업등",
price: 40000,
url: "/images/products/lamps/21-r png.png",
quantity: 1
}
],
total_order_price: "130000.00"
}
```

2021-05-20 10:05 UTC, tonic523 commented
첨부했습니다!

2021-05-20 10:39 UTC, Kang-kyunghun requested changes

2021-05-20 10:39 UTC, Kang-kyunghun commented on order/views.py
> +        orders     = user.order.all()
주문 전 상태의 order만 받아서 가져와 주세요.

2021-05-20 10:39 UTC, Kang-kyunghun commented on order/views.py
> +        order_list_qs     = order_list.annotate(price=F('product__price')*F('quantity'))
변수명 정확하게

2021-05-20 10:39 UTC, Kang-kyunghun commented on order/views.py
> +        order_list = OrderList.objects.filter(order__in=orders)
```suggestion
        carts = OrderList.objects.filter(order__status__name='주문전', user=request.user)
```

2021-05-20 10:39 UTC, Kang-kyunghun commented on order/views.py
> +            order_product          = OrderList.objects.get(id=order_id)
- get으로 요청할 때 만약 id가 없는 경우 예외처리
- 변수명 order_id -> cart_id
- save 추가

2021-05-20 10:57 UTC, tonic523 commented on order/views.py
> +            order_product          = OrderList.objects.get(id=order_id)
![스크린샷, 2021-05-20 19-56-47](https://user-images.githubusercontent.com/59171113/118967322-89f1ce00-b9a5-11eb-9c9e-622f644a4ed7.png)

2021-05-20 11:38 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-20 11:38 UTC, merged