Add : [Product App] Recommend View 추가
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #18
Opened 2021-05-18 09:54 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
추천 상품을 리스트로 response
		 
## 수정 사항들 자세한 내용
- 카테고리 중 하나를 무작위로 택하여 카테고리의 상품들을 반환

## 기타 질문 및 특이 사항
main view에 있는 추천 제품을 branch로 따로 만들어 구현했습니다.
별점은 아직 댓글 기능을 구현하지 못해서 우선 무작위로 부여하는 걸로 지정했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-19 09:53 UTC, Kang-kyunghun requested changes

2021-05-19 09:53 UTC, Kang-kyunghun commented on product/views.py
> +        category_list      = list(Category.objects.all())
List로 안 감싸도 될 것 같아요

2021-05-19 09:53 UTC, Kang-kyunghun commented on product/views.py
> +                )
list comprehension으로 바꿔보세요.

2021-05-19 11:23 UTC, tonic523 commented on product/views.py
> +                )
이중 comprehension으로 바꿨어요

2021-05-20 02:55 UTC, Kang-kyunghun requested changes

2021-05-20 02:55 UTC, Kang-kyunghun commented on product/views.py
> +        category_list      = Category.objects.all()
```suggestion
        products = Product.objects.filter(sub_category_id=sub_category_id).order_by('-stock')[:PRODUCT_LIMIT]
```

2021-05-20 05:13 UTC, Kang-kyunghun requested changes

2021-05-20 05:13 UTC, Kang-kyunghun commented on product/urls.py
> +    path('/recommended', RecommendedView.as_view())
```suggestion
    path('/recommendation', RecommendedView.as_view())
```
- 명사로 구성해 주세요.

2021-05-20 06:24 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-20 06:24 UTC, merged