Add: [User app] 회원가입 기능 추가
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #5
Opened 2021-05-12 06:45 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
- KeyError 시 에러처리
- User 테이블에 입력된 값(email, first_name and last_name, phone_number)이 존재할 때 duplicate error 처리
- password 해쉬 암호화 후 string값으로 저장
- 해쉬 암호화에 사용되는 알고리즘은 my_settings.py 에 저장

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-13 01:43 UTC, Kang-kyunghun requested changes

2021-05-13 01:43 UTC, Kang-kyunghun commented on user/views.py
> +            if User.objects.filter(phone_number = phone_number).exists():
```suggestion
            if User.objects.filter(first_name = first_name, last_name = last_name).exists():
                return JsonResponse({'message':'DUPLICATE NAME'}, status=409)
                
            if User.objects.filter(email = email).exists():
                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
                
            if User.objects.filter(phone_number = phone_number).exists():
```
- 가독성을 위해 if 절 간에 간격이 있으면 좋을 것 같습니다.
- 회원 가입을 진행할 때 유효성 검사를 진행하지 않는데, 프론트에서 한다고 해도 백엔드 입장에서는 프론트에서 들어오는 값들에 대해 100% 보장하기 어렵기 때문에 적절한 유효성 검사를 추가해 주는 것이 좋습니다.
- 유효성 검사를 추가하고 유효성 검사와 비밀번호 암호화의 순서에 대해 생각해 보세요.
- ststus code 409가 언제 발생하는지 코멘트로 남겨주세요.

2021-05-13 01:43 UTC, Kang-kyunghun commented on user/views.py
> +from my_settings    import ALGORITHM
- 알고리즘을 굳이 따로 분리 할 필요는 없지만, 따로 분리 했다면 settings.py에만 Improt해서 settings에서 가지고 오는 것이 좋을 것 같습니다.

2021-05-13 02:25 UTC, tonic523 commented on user/views.py
> +            if User.objects.filter(phone_number = phone_number).exists():
status 409는 request와 서버의 현재 상태와 충돌(conflict)했음을 알려줍니다.
회원 가입 시 입력한 이메일이 이미 가입돼 있는 이메일과 같다면 충돌했음을 알려주는 409를 쓰는게 좋을 것 같아서 사용했습니다.

2021-05-13 04:56 UTC, Kang-kyunghun commented on user/views.py
> +            if User.objects.filter(phone_number = phone_number).exists():
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409
이 글을 참고해 보면 보통 파일 업로드에서 버전 충돌 같은 상황에서 많이 사용되는 것을 볼 수 있습니다. 따라서 이 상황에서는 400이 더 낫지 않을까 생각됩니다.

2021-05-13 07:26 UTC, tonic523 commented on user/views.py
> +            if User.objects.filter(phone_number = phone_number).exists():
읽어보니깐 409는 보통 PUT 요청에 대한 응답으로 많이 사용하네요.. 400으로 수정하겠습니다.

2021-05-13 07:29 UTC, tonic523 commented on user/views.py
> +from my_settings    import ALGORITHM
분리하지 않고 직접 입력하겠습니다

2021-05-14 01:35 UTC, Kang-kyunghun requested changes

2021-05-14 01:35 UTC, Kang-kyunghun commented on user/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'),bcrypt.gensalt()).decode('utf-8')
모든 유효성 검사가 끝나고 비밀번호 암호화를 진행하는 것이 좋지 않을까요? 비밀번호 암호화를 진행했는데, 다음 유효성 검사에서 에러처리가 나면 비밀번호 암호화 하는 것에 자원이 낭비 될 것 같습니다.

2021-05-14 01:42 UTC, tonic523 commented on user/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'),bcrypt.gensalt()).decode('utf-8')
넵 유효성 검사 끝나고 다음에 암호화 진행하는 코드로 바꾸겠습니다!

2021-05-14 02:23 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-14 02:23 UTC, merged