Add : [User App] 로그인 View, Url 작성
wecode-bootcamp-korea/20-1st-WIKEA-backend pull request #6
Opened 2021-05-12 06:46 UTC by Action2theFuture

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 View 작성
- 로그인 url 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- User의 비밀번호/이메일을 통한 로그인 구현
- 로그인할 시 토큰화해서 전달하는 로직 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-13 01:37 UTC, Kang-kyunghun requested changes

2021-05-13 01:37 UTC, Kang-kyunghun commented on user/views.py
> +from my_settings import SECRET, ALGORITHM
import 라인 맞춰주세요.

2021-05-13 01:37 UTC, Kang-kyunghun commented on user/views.py
> +                return JsonResponse({"MESSAGE": "INVALID_USER"}, status=401)
user의 존재 여부를 어디서 판단을 해야할 지 생각해 보세요.

2021-05-13 04:49 UTC, Kang-kyunghun requested changes

2021-05-13 04:49 UTC, Kang-kyunghun commented on user/views.py
> +            return JsonResponse({'token':access_token, 'user_id':jwt.decode(access_token, SECRET_KEY, algorithms='HS256')}, status=200)
여기서 다시 jwt 디코더 하는 이유가 있나요?

2021-05-13 04:49 UTC, Kang-kyunghun commented on user/utils.py
> +    return wrapper()
데코레이터도 따로 브렌치 만들어서 pr 남겨주세요.

2021-05-13 04:55 UTC, tonic523 commented on user/views.py
> +            return JsonResponse({'token':access_token, 'user_id':jwt.decode(access_token, SECRET_KEY, algorithms='HS256')}, status=200)
httpie로 token에서 data값이 나오는지 확인 차 넣었습니다.
수정하겠습니다!

2021-05-14 01:33 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-14 01:33 UTC, merged